version: '3.1'
services:
  java:
    build: .
    image: searcehpost:1
    container_name: java-searcehpost
    tty: true
    ports: 
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-1:3306/demo
  db:
    image: mysql:8.0.32
    container_name: mysql-1
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
